Result of call is true.
err1
